ALTER TABLE ONLY public.admin_audit_logs ADD CONSTRAINT admin_audit_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.business_characteristics ADD CONSTRAINT business_characteristics_pkey PRIMARY KEY (business_id);
ALTER TABLE ONLY public.business_settings ADD CONSTRAINT business_settings_pkey PRIMARY KEY (user_id, setting_key);
ALTER TABLE ONLY public.business_subscription ADD CONSTRAINT business_subscription_pkey PRIMARY KEY (business_id);
ALTER TABLE ONLY public.campaign_results ADD CONSTRAINT campaign_results_campaign_id_key UNIQUE (campaign_id);
ALTER TABLE ONLY public.campaign_results ADD CONSTRAINT campaign_results_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.campaign_share_plan ADD CONSTRAINT campaign_share_plan_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.capital_assets ADD CONSTRAINT capital_assets_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.compliance_evidence ADD CONSTRAINT compliance_evidence_obligation_id_document_id_key UNIQUE (obligation_id, document_id);
ALTER TABLE ONLY public.compliance_evidence ADD CONSTRAINT compliance_evidence_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.compliance_licences ADD CONSTRAINT compliance_licences_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.compliance_obligations ADD CONSTRAINT compliance_obligations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.compliance_rules ADD CONSTRAINT compliance_rules_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.customer_channels ADD CONSTRAINT customer_channels_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.customer_interactions ADD CONSTRAINT customer_interactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.customers ADD CONSTRAINT customers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.employees ADD CONSTRAINT employees_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.expense_categories ADD CONSTRAINT expense_categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.expenses ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.finance_accounts ADD CONSTRAINT finance_accounts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.finance_audit_logs ADD CONSTRAINT finance_audit_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.finance_payments ADD CONSTRAINT finance_payments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.finance_transfers ADD CONSTRAINT finance_transfers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.income_tax_records ADD CONSTRAINT income_tax_records_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_purchase_items ADD CONSTRAINT inventory_purchase_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_purchases ADD CONSTRAINT inventory_purchases_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.market_audiences ADD CONSTRAINT market_audiences_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.marketing_activities ADD CONSTRAINT marketing_activities_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.marketing_campaigns ADD CONSTRAINT marketing_campaigns_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.marketing_reach ADD CONSTRAINT marketing_reach_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.paye_records ADD CONSTRAINT paye_records_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.permission_catalog ADD CONSTRAINT permission_catalog_pkey PRIMARY KEY (permission_key);
ALTER TABLE ONLY public.product_categories ADD CONSTRAINT product_categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.quotation_items ADD CONSTRAINT quotation_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.quotations ADD CONSTRAINT quotations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.role_permissions ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.role_permissions ADD CONSTRAINT role_permissions_role_permission_key_key UNIQUE (role, permission_key);
ALTER TABLE ONLY public.sale_items ADD CONSTRAINT sale_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sales_order_items ADD CONSTRAINT sales_order_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sales_orders ADD CONSTRAINT sales_orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sales_payments ADD CONSTRAINT sales_payments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sales ADD CONSTRAINT sales_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sales_return_items ADD CONSTRAINT sales_return_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.sales_returns ADD CONSTRAINT sales_returns_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.stock_movements ADD CONSTRAINT stock_movements_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.stock_transfers ADD CONSTRAINT stock_transfers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.suppliers ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tax_documents ADD CONSTRAINT tax_documents_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tax_expenses ADD CONSTRAINT tax_expenses_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tax_imports ADD CONSTRAINT tax_imports_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tax_purchases ADD CONSTRAINT tax_purchases_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tax_sales ADD CONSTRAINT tax_sales_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tax_settings ADD CONSTRAINT tax_settings_pkey PRIMARY KEY (user_id);
ALTER TABLE ONLY public.user_permission_overrides ADD CONSTRAINT user_permission_overrides_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_permission_overrides ADD CONSTRAINT user_permission_overrides_user_id_permission_key_key UNIQUE (user_id, permission_key);
ALTER TABLE ONLY public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);
ALTER TABLE ONLY public.vat_returns ADD CONSTRAINT vat_returns_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.warehouses ADD CONSTRAINT warehouses_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.withholding_records ADD CONSTRAINT withholding_records_pkey PRIMARY KEY (id);
CREATE INDEX admin_audit_logs_created_idx ON public.admin_audit_logs USING btree (created_at DESC);
CREATE INDEX campaign_results_campaign_idx ON public.campaign_results USING btree (campaign_id);
CREATE INDEX campaign_share_plan_campaign_idx ON public.campaign_share_plan USING btree (campaign_id);
CREATE INDEX campaign_share_plan_date_idx ON public.campaign_share_plan USING btree (publish_date);
CREATE INDEX customer_interactions_customer_idx ON public.customer_interactions USING btree (customer_id, occurred_at DESC);
CREATE INDEX customers_campaign_idx ON public.customers USING btree (acquired_campaign_id);
CREATE INDEX customers_follow_up_idx ON public.customers USING btree (user_id, next_follow_up);
CREATE INDEX customers_lifecycle_idx ON public.customers USING btree (user_id, lifecycle_stage);
CREATE INDEX customers_segment_idx ON public.customers USING btree (segment);
CREATE INDEX expense_categories_user_idx ON public.expense_categories USING btree (user_id);
CREATE INDEX idx_campaign_results_user ON public.campaign_results USING btree (user_id);
CREATE INDEX idx_campaign_share_plan_user ON public.campaign_share_plan USING btree (user_id);
CREATE INDEX idx_capital_assets_user ON public.capital_assets USING btree (user_id);
CREATE INDEX idx_compliance_evidence_user ON public.compliance_evidence USING btree (user_id);
CREATE INDEX idx_compliance_licences_user ON public.compliance_licences USING btree (user_id);
CREATE INDEX idx_compliance_obligations_user ON public.compliance_obligations USING btree (user_id);
CREATE INDEX idx_compliance_rules_user ON public.compliance_rules USING btree (user_id);
CREATE INDEX idx_customer_channels_user ON public.customer_channels USING btree (user_id);
CREATE INDEX idx_customers_user ON public.customers USING btree (user_id);
CREATE INDEX idx_employees_user ON public.employees USING btree (user_id);
CREATE INDEX idx_expenses_user ON public.expenses USING btree (user_id);
CREATE INDEX idx_finance_accounts_user ON public.finance_accounts USING btree (user_id);
CREATE INDEX idx_finance_audit_logs_user ON public.finance_audit_logs USING btree (user_id);
CREATE INDEX idx_finance_payments_user ON public.finance_payments USING btree (user_id);
CREATE INDEX idx_finance_transfers_user ON public.finance_transfers USING btree (user_id);
CREATE INDEX idx_income_tax_records_user ON public.income_tax_records USING btree (user_id);
CREATE INDEX idx_inventory_purchase_items_user ON public.inventory_purchase_items USING btree (user_id);
CREATE INDEX idx_inventory_purchases_user ON public.inventory_purchases USING btree (user_id);
CREATE INDEX idx_market_audiences_user ON public.market_audiences USING btree (user_id);
CREATE INDEX idx_marketing_campaigns_user ON public.marketing_campaigns USING btree (user_id);
CREATE INDEX idx_paye_records_user ON public.paye_records USING btree (user_id);
CREATE INDEX idx_product_categories_user ON public.product_categories USING btree (user_id);
CREATE INDEX idx_products_user ON public.products USING btree (user_id);
CREATE INDEX idx_quotation_items_quotation ON public.quotation_items USING btree (quotation_id);
CREATE INDEX idx_quotation_items_user ON public.quotation_items USING btree (user_id);
CREATE INDEX idx_quotations_user ON public.quotations USING btree (user_id);
CREATE INDEX idx_sale_items_sale ON public.sale_items USING btree (sale_id);
CREATE INDEX idx_sale_items_user ON public.sale_items USING btree (user_id);
CREATE INDEX idx_sales_customer ON public.sales USING btree (customer_id);
CREATE INDEX idx_sales_order_items_order ON public.sales_order_items USING btree (order_id);
CREATE INDEX idx_sales_order_items_user ON public.sales_order_items USING btree (user_id);
CREATE INDEX idx_sales_orders_user ON public.sales_orders USING btree (user_id);
CREATE INDEX idx_sales_payments_sale ON public.sales_payments USING btree (sale_id);
CREATE INDEX idx_sales_payments_user ON public.sales_payments USING btree (user_id);
CREATE INDEX idx_sales_return_items_return ON public.sales_return_items USING btree (return_id);
CREATE INDEX idx_sales_return_items_user ON public.sales_return_items USING btree (user_id);
CREATE INDEX idx_sales_returns_user ON public.sales_returns USING btree (user_id);
CREATE INDEX idx_sales_user ON public.sales USING btree (user_id);
CREATE INDEX idx_stock_movements_user ON public.stock_movements USING btree (user_id);
CREATE INDEX idx_stock_transfers_user ON public.stock_transfers USING btree (user_id);
CREATE INDEX idx_suppliers_user ON public.suppliers USING btree (user_id);
CREATE INDEX idx_tax_documents_sale_id ON public.tax_documents USING btree (sale_id);
CREATE INDEX idx_tax_documents_user ON public.tax_documents USING btree (user_id);
CREATE INDEX idx_tax_expenses_user ON public.tax_expenses USING btree (user_id);
CREATE INDEX idx_tax_imports_user ON public.tax_imports USING btree (user_id);
CREATE INDEX idx_tax_purchases_user ON public.tax_purchases USING btree (user_id);
CREATE INDEX idx_tax_sales_user ON public.tax_sales USING btree (user_id);
CREATE INDEX idx_tax_settings_user ON public.tax_settings USING btree (user_id);
CREATE INDEX idx_vat_returns_user ON public.vat_returns USING btree (user_id);
CREATE INDEX idx_warehouses_user ON public.warehouses USING btree (user_id);
CREATE INDEX idx_withholding_records_user ON public.withholding_records USING btree (user_id);
CREATE INDEX market_audiences_user_idx ON public.market_audiences USING btree (user_id);
CREATE INDEX marketing_activities_user_date_idx ON public.marketing_activities USING btree (user_id, activity_date DESC);
CREATE INDEX marketing_reach_user_period_idx ON public.marketing_reach USING btree (user_id, period);
CREATE INDEX role_permissions_role_idx ON public.role_permissions USING btree (role);
CREATE INDEX tax_expenses_campaign_idx ON public.tax_expenses USING btree (campaign_id);
CREATE INDEX tax_expenses_recurring_idx ON public.tax_expenses USING btree (user_id, is_recurring, next_due_date);
ALTER TABLE ONLY public.campaign_results ADD CONSTRAINT campaign_results_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.marketing_campaigns(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.campaign_share_plan ADD CONSTRAINT campaign_share_plan_audience_id_fkey FOREIGN KEY (audience_id) REFERENCES public.market_audiences(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.campaign_share_plan ADD CONSTRAINT campaign_share_plan_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.marketing_campaigns(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.campaign_share_plan ADD CONSTRAINT campaign_share_plan_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.customer_channels(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.compliance_evidence ADD CONSTRAINT compliance_evidence_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.tax_documents(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.compliance_evidence ADD CONSTRAINT compliance_evidence_obligation_id_fkey FOREIGN KEY (obligation_id) REFERENCES public.compliance_obligations(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.compliance_licences ADD CONSTRAINT compliance_licences_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.tax_documents(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.compliance_licences ADD CONSTRAINT compliance_licences_obligation_id_fkey FOREIGN KEY (obligation_id) REFERENCES public.compliance_obligations(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.compliance_obligations ADD CONSTRAINT compliance_obligations_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.tax_documents(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.compliance_obligations ADD CONSTRAINT compliance_obligations_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES public.compliance_rules(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.customer_interactions ADD CONSTRAINT customer_interactions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.customers ADD CONSTRAINT customers_acquired_campaign_id_fkey FOREIGN KEY (acquired_campaign_id) REFERENCES public.marketing_campaigns(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.customers ADD CONSTRAINT customers_audience_id_fkey FOREIGN KEY (audience_id) REFERENCES public.market_audiences(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.customers ADD CONSTRAINT customers_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.customer_channels(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.customers ADD CONSTRAINT customers_converted_sale_id_fkey FOREIGN KEY (converted_sale_id) REFERENCES public.sales(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.finance_payments ADD CONSTRAINT finance_payments_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.finance_accounts(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.finance_payments ADD CONSTRAINT finance_payments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.finance_payments ADD CONSTRAINT finance_payments_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.finance_transfers ADD CONSTRAINT finance_transfers_from_account_id_fkey FOREIGN KEY (from_account_id) REFERENCES public.finance_accounts(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.finance_transfers ADD CONSTRAINT finance_transfers_to_account_id_fkey FOREIGN KEY (to_account_id) REFERENCES public.finance_accounts(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.inventory_purchase_items ADD CONSTRAINT inventory_purchase_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.inventory_purchase_items ADD CONSTRAINT inventory_purchase_items_purchase_id_fkey FOREIGN KEY (purchase_id) REFERENCES public.inventory_purchases(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.inventory_purchases ADD CONSTRAINT inventory_purchases_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.inventory_purchases ADD CONSTRAINT inventory_purchases_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.marketing_activities ADD CONSTRAINT marketing_activities_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.marketing_campaigns(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.marketing_activities ADD CONSTRAINT marketing_activities_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.tax_expenses(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.marketing_campaigns ADD CONSTRAINT marketing_campaigns_audience_id_fkey FOREIGN KEY (audience_id) REFERENCES public.market_audiences(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.marketing_reach ADD CONSTRAINT marketing_reach_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.marketing_campaigns(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.marketing_reach ADD CONSTRAINT marketing_reach_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES public.customer_channels(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_categories(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.products ADD CONSTRAINT products_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.products ADD CONSTRAINT products_warehouse_id_fkey FOREIGN KEY (warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.quotation_items ADD CONSTRAINT quotation_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.quotation_items ADD CONSTRAINT quotation_items_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.quotations(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.quotations ADD CONSTRAINT quotations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.role_permissions ADD CONSTRAINT role_permissions_permission_key_fkey FOREIGN KEY (permission_key) REFERENCES public.permission_catalog(permission_key) ON DELETE CASCADE;
ALTER TABLE ONLY public.sale_items ADD CONSTRAINT sale_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.sale_items ADD CONSTRAINT sale_items_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.sales ADD CONSTRAINT sales_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.sales_order_items ADD CONSTRAINT sales_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.sales_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.sales_order_items ADD CONSTRAINT sales_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.sales_orders ADD CONSTRAINT sales_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.sales_payments ADD CONSTRAINT sales_payments_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.sales_return_items ADD CONSTRAINT sales_return_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.sales_return_items ADD CONSTRAINT sales_return_items_return_id_fkey FOREIGN KEY (return_id) REFERENCES public.sales_returns(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.sales_returns ADD CONSTRAINT sales_returns_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.stock_movements ADD CONSTRAINT stock_movements_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.stock_transfers ADD CONSTRAINT stock_transfers_from_warehouse_id_fkey FOREIGN KEY (from_warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.stock_transfers ADD CONSTRAINT stock_transfers_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.stock_transfers ADD CONSTRAINT stock_transfers_to_warehouse_id_fkey FOREIGN KEY (to_warehouse_id) REFERENCES public.warehouses(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.tax_documents ADD CONSTRAINT tax_documents_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.tax_sales(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.tax_expenses ADD CONSTRAINT tax_expenses_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.marketing_campaigns(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.tax_expenses ADD CONSTRAINT tax_expenses_recurring_parent_id_fkey FOREIGN KEY (recurring_parent_id) REFERENCES public.tax_expenses(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.tax_expenses ADD CONSTRAINT tax_expenses_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.user_permission_overrides ADD CONSTRAINT user_permission_overrides_permission_key_fkey FOREIGN KEY (permission_key) REFERENCES public.permission_catalog(permission_key) ON DELETE CASCADE;